name: "CI"

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CodeQL:
    name: "CodeQL Code Analysis"

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: javascript
        config-file: ./.github/codeql/codeql-config.yml

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

  BuildAnalyzeAndTest:
    name: Build & Test

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: install dependencies common
      run: npm ci
      working-directory: common
    - name: install dependencies app
      run: npm ci
      working-directory: app
    - name: install dependencies action
      run: npm ci
      working-directory: action
    - name: build app
      run: npm run build
      working-directory: app

    - name: test common
      run: npm run test
      working-directory: common

    - name: build and test action
      run: npm run all
      working-directory: action

    - name: build and test app
      run: npm run all
      working-directory: app

    
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: |
          common/reports/junit.xml
          app/reports/**/junit.xml
          action/reports/junit.xml

    - name: publish coverage for common
      uses: danhunsaker/clover-reporter-action@v0.2.17-clover
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        clover-file: common/coverage/clover.xml

    - name: publish coverage for common
      uses: danhunsaker/clover-reporter-action@v0.2.17-clover
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        clover-file: app/coverage/clover.xml

    - name: publish coverage for common
      uses: danhunsaker/clover-reporter-action@v0.2.17-clover
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        clover-file: action/coverage/clover.xml
